# -*- coding: utf-8 -*-
"""Avanish Salunke

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DVa-2GaLUiraVXu-gCU7S8hslXrzqLPQ
"""

import numpy as np

## Basic numpy array creation and data checking
arr = np.array([10, 20, 30, 40, 50])
arr2 = np.array([[10, 20.0, 30], [40, 50, 60]])
print(arr)
print(arr2)
print("Shape of array 2 :", arr2.shape)
print("size of array 2 :", arr2.size)
print("the no of dimensions in array 2 :", arr2.ndim)
print("datatype for array 2 :", arr2.dtype)
print("space taken by each element in array 2 :", arr2.itemsize)
print("space taken by each element in array 1 :", arr.itemsize)

arr = np.zeros((4,3))
print(arr)

arr = np.ones((3,4))
print(arr)

arr = np.empty((5,5))
print(arr)

arr = np.eye(5 , k = 1)
print(arr)

arr = np.identity(5)
print(arr)

arr = np.arange(1,11)
print(arr)
arr = np.arange(1,11,2)
print(arr)

arr = np.linspace(1,11,3)
print(arr)

arr = np.logspace(1,4,10)
print(arr)

## resizing the data

arr = np.arange(1,16)
print(arr)
arr_reshape = np.reshape(arr, (3,5))
print("reshaped array :")
print(arr_reshape)

arr_flatten = arr_reshape.flatten()
print("array after flattening")
print(arr_flatten)

arr_ravel = arr_reshape.ravel()
print("array after appying the ravel function :")
print(arr_ravel)

arr = np.ones((4,5))
print("shape of the array before applying transpose :" , arr.shape)
print("shape of the array after applying transpose :", arr.T.shape)

print("array before resizing it :")
print(arr)

print("array after resizing it to 3*6")
arr.resize((3,6))
print(arr)

arr = np.ones((200,100,3))
print("shape of the array before swapaxes :", arr.shape)
arr1 = np.swapaxes(arr, 0, 2)
print("shape of the array after swapaxes :", arr1.shape)

arr = [10, 20, 30, 40, 50, 60]
print("sum of the array :", np.sum(arr))
print("mean of the array :", np.mean(arr))
print("median of the array :", np.median(arr))
print("standard deviation of the array :", np.std(arr))
print("variance of the array :", np.var(arr))
print("min number in the array :", np.min(arr))
print("maximum number in the array :", np.max(arr))
print("index of the min number :", np.argmin(arr))
print("index of the max number :", np.argmax(arr))
print("product of all the numbers in the arra : ", np.prod(arr))
print("taking square roots of all element :", np.sqrt(arr))
print("squaring the whole array : ", np.square(arr))
print("arr raised to some power :", np.power(arr, 3))
print("e raise to the elements in the  array", np.exp(arr))
print("logs of the values : ", np.log(arr))

arr = [10, 20, -30, -40, -50, -60]
print("absoolute values of the array :", np.abs(arr))

arr = [10, 13.4, 14.3, 13.4, 66.5]
print("rounding off to nearest integers : ", np.round(arr))

arr = [10, 20, 30, 40, 50, 60]
print("clip the values in the array from 20 to 50 :", np.clip(arr, 20, 50))

## statistical functions :

arr1 = [10,20,30,40,50,60]
arr2 = [60, 50, 40, 30, 78, 88]
print("value at the 50th percentage in array :", np.percentile(arr1, 50))
print("same thing as pecentile but with decimel value :", np.quantile(arr1, 0.5))
print("relation between coef of arr1 and arr2 :", np.corrcoef(arr1,arr2))
print("the hard part :", np.cov(arr1, arr2))

counts, edges = np.histogram(arr1, bins = 3)
print("counts of the numbers in each bucket :", counts)
print("the range of the distribution :", edges)

## rnadom functions :

arr = [10, 20, 30, 40 , 50, 60]
print("pick up 3 random numbers from 0 to 1 :", np.random.rand(3))
print("pick up 3 random numbers from well distribution :", np.random.randn(3))
print("pcik up 3 numbers from our given range :", np.random.randint(1,10,3))
print("pick up 3 numbers from our array :", np.random.choice(arr, 3))
print("shuffle our array :", np.random.shuffle(arr))
print("premute our array :", np.random.permutation(arr))

np.random.seed(42)
print("check 1 after seeding :", np.random.rand(3))

np.random.seed(42)
print("check 2 after seeding :", np.random.rand(3))

## matrix multiplication and linear algebra

arr1 = [1, 2, 3]
arr2 = [4, 5, 6]

print("dot product :", np.dot(arr1,arr2))
print("inner product :", np.inner(arr1, arr2))

arr3 = ([[1, 2], [3, 4]])
arr4 = ([[5, 6], [7, 8]])

print("matrix multiplication :", np.matmul(arr3, arr4))
print("outer product :", np.outer(arr3, arr4))

arr5 = [1, 0, 0]
arr6 = [0, 0, 1]
print("cross product :", np.cross(arr5, arr6))

print("inverse of arr 3 :", np.linalg.inv(arr3))
print("determinant of arr 3 :", np.linalg.det(arr3))

eigenvalues, eigenvectors = np.linalg.eig(arr3)
print("finding the eigen values for arr 3 :", eigenvalues, eigenvectors )
print("distance from the (0,0) point for arr 3 :", np.linalg.norm(arr3))

arr7 = np.array([11,9])
print("find values for x and y for arr 3 : ", np.linalg.solve(arr3,arr7))

## sorting functions

arr = np.array([10,40,20, 20, 20, 60,50])
print("this is the sorted array :", np.sort(arr))
print("this is the implementation of the arg sort function", np.argsort(arr))
print("this will return a unique array :", np.unique(arr))
types, counts = np.unique(arr, return_counts = True)
print("types :" , types)
print("counts :", counts)

arr = np.array([-10, 20 , 30 , -40, -50, 70])
print("replace all negatives with 0 :", np.where(arr<0,0,arr))

arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([50, 60, 70, 80])
arr3 = np.array([100, 110, 120, 130])

print("arrays after stacking vertically :", np.vstack((arr1, arr2, arr3)))
print("arrays after stacking horizontally :", np.hstack((arr1, arr2, arr3)))

arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[3, 4], [5, 6]])

print("this is the concatanation of the array")
print("this is the vertical concatenation")
print(np.concatenate((arr1, arr2), axis = 0))
print("this is the horrizontal concatenation")
print(np.concatenate((arr1, arr2), axis = 1))


arr1 = np.array([10, 20 , 30 , 40 , 50, 60])
pieces = np.split(arr1 , 3)
print("pices : ", pieces)

## Read data using PANDAS

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")
df.to_excel("tips.xlsx", index = False)
df = pd.read_excel("tips.xlsx")
df.to_json("tips.json" , orient = "records")
df = pd.read_json("tips.json")

## data inspection

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

print("the top 10 rows")
print(df.head(10), "\n")

print("the last 10 rows")
print(df.tail(10), "\n")

print("this is the information about the data")
print(df.info(), "\n")

print("this will describe the datatset")
print(df.describe())

table_shape = df.shape
print("this is the shape of the data :", table_shape)

names = df.columns
print("this are the names of the columns : ", names)

row_names = df.index
print("this is the names of the rows: ", row_names)

print("this is the data types for each column :", df.dtypes)

## selection

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

iloc_data = df.iloc[0:3 , 0:2]
print("first 3 rows and first 2 columns :")
print(iloc_data, "\n")


loc_data = df.loc[0:3, ['day', 'time', 'tip']]
print(loc_data, "\n")


iat_data = df.iat[1,2]
print("this is specific data using iat: ", iat_data, "\n")

at_data = df.at[1, 'tip']
print("this is the specific data using at :", at_data, "\n")

## missing values

import pandas as pd
import numpy as np

data = {
    'name': ['Alice', 'Bob', np.nan, 'David'],
    'age': [25, np.nan, 30, 35],
    'score': [85, 90, np.nan, -99]
}
df = pd.DataFrame(data)

isnull_data = df.isnull()
print("isnull data:")
print(isnull_data, "\n")

notnull_data = df.notnull()
print("notnull data:")
print(notnull_data, "\n")

dropna_data = df.dropna()
print("dropna data:")
print(dropna_data, "\n")

fillna_data = df.fillna(0)
print("fillna data:")
print(fillna_data, "\n")

replace_data = df.replace(-99, 0)
print("replace data:")
print(replace_data, "\n")

## data manipulation

import pandas as pd

df1 = pd.DataFrame({'id': [1, 2, 3], 'cat': ['A', 'B', 'A'], 'val': [10, 20, 30]})
df2 = pd.DataFrame({'id': [2, 3, 4], 'score': [99, 88, 77]})

drop_data = df1.drop(columns=['cat'])
print("drop data:")
print(drop_data, "\n")

rename_data = df1.rename(columns={'cat': 'category'})
print("rename data:")
print(rename_data, "\n")

sort_val_data = df1.sort_values(by='val', ascending=False)
print("sort_values data:")
print(sort_val_data, "\n")

sort_idx_data = df1.sort_index(ascending=False)
print("sort_index data:")
print(sort_idx_data, "\n")

groupby_data = df1.groupby('cat')['val'].sum()
print("groupby data:")
print(groupby_data, "\n")

merge_data = pd.merge(df1, df2, on='id', how='inner')
print("merge data:")
print(merge_data, "\n")

join_data = df1.set_index('id').join(df2.set_index('id'), how='inner')
print("join data:")
print(join_data, "\n")

concat_data = pd.concat([df1, df2])
print("concat data:")
print(concat_data, "\n")

pivot_df = pd.DataFrame({
    'date': ['Mon', 'Mon', 'Tue', 'Tue'],
    'city': ['NY', 'LA', 'NY', 'LA'],
    'temp': [60, 75, 62, 78]
})

pivot_data = pivot_df.pivot(index='date', columns='city', values='temp')
print("pivot data:")
print(pivot_data, "\n")

pivot_table_data = pivot_df.pivot_table(index='city', values='temp', aggfunc='mean')
print("pivot_table data:")
print(pivot_table_data, "\n")

melt_data = pd.melt(pivot_df, id_vars=['date', 'city'], value_vars=['temp'])
print("melt data:")
print(melt_data, "\n")

## statistics

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

mean_data = df['total_bill'].mean()
print("mean data:")
print(mean_data, "\n")

median_data = df['total_bill'].median()
print("median data:")
print(median_data, "\n")

mode_data = df['day'].mode()
print("mode data:")
print(mode_data, "\n")

std_data = df['total_bill'].std()
print("std data:")
print(std_data, "\n")

var_data = df['total_bill'].var()
print("var data:")
print(var_data, "\n")

corr_data = df[['total_bill', 'tip', 'size']].corr()
print("corr data:")
print(corr_data, "\n")

cov_data = df[['total_bill', 'tip', 'size']].cov()
print("cov data:")
print(cov_data, "\n")

value_counts_data = df['day'].value_counts()
print("value_counts data:")
print(value_counts_data, "\n")

unique_data = df['day'].unique()
print("unique data:")
print(unique_data, "\n")

nunique_data = df['day'].nunique()
print("nunique data:")
print(nunique_data, "\n")

## graphs using matplotlib

import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))

plt.plot([1, 2, 3, 4], [10, 20, 25, 30])
plt.show()

plt.scatter([1, 2, 3, 4], [10, 20, 25, 30])
plt.show()

plt.bar(['A', 'B', 'C', 'D'], [10, 20, 25, 30])
plt.show()

plt.barh(['A', 'B', 'C', 'D'], [10, 20, 25, 30])
plt.show()

data = [1, 2, 2, 3, 3, 3, 4, 4, 5]
plt.hist(data, bins=5)
plt.show()

plt.pie([15, 30, 45, 10], labels=['Apples', 'Bananas', 'Cherries', 'Dates']);

data = [10, 15, 20, 25, 30, 50]
plt.boxplot(data)
plt.show()

data = [10, 15, 20, 25, 30, 50]
plt.violinplot(data)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

image_data = np.random.rand(10, 10)
plt.imshow(image_data, cmap='viridis')
plt.show()

plt.subplot(1, 2, 1)
plt.plot([1, 2, 3], [10, 20, 30])

plt.subplot(1, 2, 2)
plt.scatter([1, 2, 3], [10, 20, 30])
plt.show()

plt.plot([1, 2, 3, 4], [10, 20, 25, 30], label="Sales Growth")

plt.title("My Formatted Plot")
plt.xlabel("X-Axis (Time)")
plt.ylabel("Y-Axis (Value)")
plt.legend()
plt.grid(True)

plt.savefig("my_formatted_graph.png")
plt.show()

## Dataset manipulation using Sklearn

from sklearn.datasets import load_iris, load_digits, fetch_california_housing
from sklearn.datasets import make_classification, make_regression
from sklearn.model_selection import train_test_split

iris = load_iris()
X_iris, y_iris = iris.data, iris.target
print("Iris dataset shape:", X_iris.shape, y_iris.shape, "\n")

digits = load_digits()
X_digits, y_digits = digits.data, digits.target
print("Digits dataset shape:", X_digits.shape, y_digits.shape, "\n")

california = fetch_california_housing()
X_cali, y_cali = california.data, california.target
print("California Housing dataset shape:", X_cali.shape, y_cali.shape, "\n")

X_class, y_class = make_classification(n_samples=100, n_features=5, random_state=42)
print("Generated classification shape:", X_class.shape, y_class.shape, "\n")

X_reg, y_reg = make_regression(n_samples=100, n_features=5, noise=0.1, random_state=42)
print("Generated regression shape:", X_reg.shape, y_reg.shape, "\n")

X_train, X_test, y_train, y_test = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

## Preprocessing

import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, Normalizer
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, PolynomialFeatures

num_data = np.array([[1.0, 20.0], [2.0, 40.0], [3.0, 60.0]])
cat_data_1d = np.array(['red', 'blue', 'green', 'red'])
cat_data_2d = np.array([['low', 'S'], ['high', 'L'], ['medium', 'M']])

std_data = StandardScaler().fit_transform(num_data)
print("StandardScaler data:")
print(std_data, "\n")

minmax_data = MinMaxScaler().fit_transform(num_data)
print("MinMaxScaler data:")
print(minmax_data, "\n")

robust_data = RobustScaler().fit_transform(num_data)
print("RobustScaler data:")
print(robust_data, "\n")

norm_data = Normalizer().fit_transform(num_data)
print("Normalizer data:")
print(norm_data, "\n")

le_data = LabelEncoder().fit_transform(cat_data_1d)
print("LabelEncoder data:")
print(le_data, "\n")

ohe_data = OneHotEncoder(sparse_output=False).fit_transform(cat_data_2d)
print("OneHotEncoder data:")
print(ohe_data, "\n")

oe_data = OrdinalEncoder().fit_transform(cat_data_2d)
print("OrdinalEncoder data:")
print(oe_data, "\n")

poly_data = PolynomialFeatures(degree=2).fit_transform(num_data)
print("PolynomialFeatures data:")
print(poly_data, "\n")

## Model validation

from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, GridSearchCV, RandomizedSearchCV, KFold, StratifiedKFold

X, y = make_classification(n_samples=100, n_features=5, random_state=42)
model = RandomForestClassifier(random_state=42)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
print("KFold splits:", kf.get_n_splits(X), "\n")

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
print("StratifiedKFold splits:", skf.get_n_splits(X, y), "\n")

cv_scores = cross_val_score(model, X, y, cv=kf)
print("cross_val_score data:")
print(cv_scores, "\n")

param_grid = {'n_estimators': [10, 50], 'max_depth': [None, 5]}
grid_search = GridSearchCV(model, param_grid, cv=3)
grid_search.fit(X, y)
print("GridSearchCV best params:")
print(grid_search.best_params_, "\n")

param_dist = {'n_estimators': [10, 50, 100], 'max_depth': [None, 5, 10]}
random_search = RandomizedSearchCV(model, param_dist, n_iter=3, cv=3, random_state=42)
random_search.fit(X, y)
print("RandomizedSearchCV best params:")
print(random_search.best_params_, "\n")